### ISSUE TITLE
Undefined after login

### ISSUE THREAD

**Issue by harishsn** [takayukii/example-Laravelchat-Echo-Socket.io#1]
L A R A V E L  E C H O  S E R V E R

version 1.1.2

⚠Starting server in DEV mode...

✔ Running at localhost on port 6001
✔ Channels are ready.
✔ Listening for http events...
✔ Listening for redis events...

Server ready!

[12:21:35 PM] - -jhxRdOcFTsRCNHyAAAA left channel: private-user.2
undefined:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:28:34)
    at Request.self.callback (/usr/lib/node_modules/laravel-echo-server/node_modules/request/request.js:186:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/request/request.js:1081:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

My laravel-echo-server.json file

{
    "appKey": "9te930q989itok355krkfrs95j92ais01iim3i5sjs1k93g87kt8qdd0ur91",
    "authEndpoint": "/broadcasting/auth",
    "authHost": "http://localhost:8000",
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": true,
    "host": "localhost",
    "port": "6001",
    "protocol": "ws",
    "referrers": [],
    "sslCertPath": "",
    "sslKeyPath": "",
    "verifyAuthPath": true,
    "verifyAuthServer": false
}

**Comment by d-pollard** [comment]
How did you fix this??
